### ISSUE TITLE
Range of plot does not update

### ISSUE THREAD

**Issue by maikherbig** [ZELLMECHANIK-DRESDEN/ShapeOut#204] opened 2018-01-23 09:39 UTC
If I
-Load several measurements
-Show contour plot
I can not change the plotting region (in Plotting tab) anymore.
After hitting Apply, the changes are not used.
Only when I remove the conotur plot, I can change the plotting region again.

**Comment by paulmueller** [comment] 2018-01-23 21:13
I strongly believe this is a duplicate of #201. Thanks for the hint with the contour plot.

**Closed by paulmueller** 2018-01-23 21:13 UTC
Labels: duplicate
