### ISSUE TITLE
Clicking data point in fluorescence plot does not show correct event

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/ShapeOut#246] opened 2019-07-01 08:43 UTC
I was checking events for their fluorescence and found that the value I click in the plot window doesn't match at all the fluorescence trace that is displayed (see image below). I checked in dclab if the value for the events is assigned wrongly but their the data for fl2_max fits the corresponding trace (also for fl1 and fl3). So, I guess clicking in the plot just picks a wrong event to display. I found this in the following dataset:
`\\biotec-files\experiments_18_19\20190627_Felix_WBCs_lonchannel\Dexfrac_CD3_19_56_stained\M004_data.rtdc`

![image](https://user-images.githubusercontent.com/19806005/60422725-e3538700-9bec-11e9-82ae-d0d3c27fa03b.png)

**Comment by paulmueller** [comment] 2019-07-01 08:48
duplicate of #244 
This is fixed in Shape-Out 0.9.4

**Closed by paulmueller** 2019-07-01 08:48 UTC
Labels: duplicate
