### ISSUE TITLE
Reset of parameters

### ISSUE THREAD

**Issue by DerDeef** [ZELLMECHANIK-DRESDEN/ShapeOut#75] opened 2016-06-28 17:51 UTC
When a measurement is added or removed and the whole set re-analysed, the parameters of the contour plots are reset to default or the newly calculated values, except the width. Could you include a "fix parameters" checkbox?

**Comment by paulmueller** [comment] 2016-06-28 19:50
Is this a duplicate of #9 ?
Did you try the "Contour Fix Scale" checkbox?

**Comment by DerDeef** [comment] 2016-06-28 20:08
ahhh. i thought "scale" is the range setting of the axis which would be kept. 
so if you could add, that the colour coding also stays when checking the contour fix scale button it would be great. 
my "problem":
when i have 10 plots in comparison and want to quickly add or remove a sinlge plot in the contour plot, i add or remove a measurement and re-analyse. when i have 5 plots in red and 5 in green, after re-analysing i have all 10 back in the default colour. but i just realized i can simply use white colour to add or remove contour plots virtually....so just add this feature, when its not too complicated.
hope i somehow was able to explain my problem.
cheers

**Comment by paulmueller** [comment] 2016-06-28 20:51
When the number of analyzed measurements does not change for a new analysis, the colors remain the same when a new analysis is started (this is a feature, but it does not help you if you want to explicitly remove or add measurements).

The question is, how the program should determine the measurement color internally. Every measurement has a unique identifier. So in principle, this identifier could be used to map the colors. This would solve your problems and could be a hidden feature (no checkbox to en- or disable).

On the other hand, there is a feature request for analyzing the same measurement in two separate plots. What would be the best way to handle the color situation here?

**Comment by paulmueller** [comment] 2016-12-16 15:16
I am closing this, because I think this is solved by #9 or #87.
Please open a new issue if that is not the case.

**Closed by paulmueller** 2016-12-16 15:16 UTC
Labels: feedback required
