### ISSUE TITLE
Cannot update plotting range when contour plot is activated

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/ShapeOut#208] opened 2018-02-21 14:53 UTC
When checking the checkbox "contour plot" in the contour plot section, I cannot change the plotting range in the plotting section anymore. This only works by unchecking the checkbox, pressing apply in the plotting section twice with the new plot values and then reactivating the contour plot.
The whole office would be really grateful if this could be fixed with the next version. 

Thanks.

Best,
Felix

**Comment by paulmueller** [comment] 2018-02-21 17:08
looks like a duplicate of #201 and #204

**Closed** 2018-02-21 17:09 UTC
Labels: duplicate
