### ISSUE TITLE
Separate panel handling

### ISSUE THREAD

**Issue by chrherold** [ZellMechanik-Dresden/ShapeOut#13] opened 2015-08-21 06:45 UTC
1. allow to use independent (polygon)-filters for each panel
2. allow independent statistics for each panel (choosable percentiles, mean, nr of points)
3. allow export of filtered data points in (two) column table for use in other plotting tools

**Comment by paulmueller** [comment] 2015-09-07 21:46
1. This is possibly a duplicate of point 1 in issue #7? Please comment there.
2. This is a duplicate of issue #6.
3. I believe this also belongs to issue #6. Please comment there how the exported data should look like.

**Comment by paulmueller** [comment] 2015-10-03 13:20
Moving the export request of point 3 to issue #22. I believe the others are duplicate.

**Closed by paulmueller** 2015-10-03 13:20 UTC
Labels: duplicate
