### ISSUE TITLE
Program crash after approx. 30-40 times plotting

### ISSUE THREAD

**Issue by DerDeef** [ZELLMECHANIK-DRESDEN/ShapeOut#187] opened 2017-11-09 09:17 UTC
Hi Paul,
this bug can be constisently repeated:
load a data set, press 37 times apply in the plotting tab, ShapeOut "crashes"
crashing means not completely freezing, but only the first two or three tabs in the menu are filled with content, the others are empty. Buttons can be pressed, but e.g. the saving dialog does not contain buttons...see screenshot

This is independent of the size or type of data set. Funny is, on my computer it occurs after 33x on two other computers after 37x.
![bug1](https://user-images.githubusercontent.com/16649633/32597445-0adba836-c537-11e7-938a-74f25c8e2cfc.png)

**Comment by DerDeef** [comment] 2017-11-09 09:20
Philipps wrote you an Email. He is talking about the same problem.

**Comment by chrherold** [comment] 2017-11-10 10:02
The reason seems to be memory leakage. 
There are about 13 Mb additional private memory assigned to the application per click on apply.

**Comment by paulmueller** [comment] 2017-11-10 11:48
This is a known design problem in ShapeOut that is most-likely connected to the use of chaco. Ultimately, this will be fixed by #150.

**Comment by maikherbig** [comment] 2017-12-16 15:40
I just tried a few older versions of shapeout:
The problem starts at version 0.5.8. Earlier versions dont have this bug.

**Comment by paulmueller** [comment] 2017-12-18 11:44
Thanks @maikherbig!
for the record, these are the changes between 0.5.7 and 0.5.7:

https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/compare/0.5.7...0.5.8

I could not spot anything in the diffs. There are 33 commits, some of which have no builds on appveyor. It should be straight forward to download all of the successfull builds (click on green checkmark left of the commit hash to get to the appveyor build and then on "artifacts" to download) and see when the memory leak was introduced. I will have a look as soon as possible, which will probably be in January.

**Comment by maikherbig** [comment] 2017-12-18 13:45
ShapeOut_0.5.7.dev11_win_32bit_setup.exe - works
ShapeOut_0.5.7.dev12_win_32bit_setup.exe - crashes

**Comment by paulmueller** [comment] 2017-12-18 22:47
Thanks again! Looks like this is related to wxPython then. I will look into it.

**Comment by paulmueller** [comment] 2017-12-20 14:46
Update: I could not find anything in this commit that would introduce the memory leak: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/commit/64a4bf26ca3c9029a6575beeae195fbe30748c8c

**Comment by paulmueller** [comment] 2017-12-22 11:03
I managed to get rid of the memory leak (at least on Linux). It was caused by
(a) a workaround for a weird panel-redrawing issue that does not seem to be existent anymore
(b) a design issue when drawing plots (a new plotting container was created for each new analysis)

Please check out the development version and let me know whether this issue is now resolved:

https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.814/job/w7o9mlqr5bd0uohh/artifacts

**Comment by maikherbig** [comment] 2017-12-22 11:52
I installed it and pushed apply like 70 times. Only in the filter-tab the refreshing of all the panels takes now a second, which is rather long but it all works :)
After hitting "apply" 40 times in the filter-tab and also like 30 times in the plotting-tab and then quickly changing to the scatter plot-tab and clicking "downsampling" causes an error-popup (see image attached). But this is not a problem. One can easyly close the error and continue as usual.
![so_erorr](https://user-images.githubusercontent.com/14074051/34297174-e15202f6-e716-11e7-82e6-4caa4f5034ba.png)

**Comment by chrherold** [comment] 2017-12-22 12:17
Perfect, the memory leak when pressing apply is gone!

One thing I noticed when testing the new version is that after pressing apply the scrollbars, e.g. in the filter tab, disappear. They reappear after manual resizing of the window part. Do you see the same on Linux?

**Comment by paulmueller** [comment] 2017-12-23 13:23
- the PyDeadObjectError is now ignored because it is harmless; I could not reproduce it
- I tried to fix the scrollbar bug. I don't see it on Linux. (https://stackoverflow.com/questions/26442258/scrollbar-disappears-refresh-not-working-in-wx-python)
- I also tried to improve speed a little

Please have another look:
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.817/job/llewqsmajntdwvyi/artifacts

**Comment by chrherold** [comment] 2017-12-23 19:09
The scrollbar bug under Windows seems fixed. Great. Thank You.

**Closed** 2017-12-30 14:16 UTC
Labels: bug
