### ISSUE TITLE
"Contour fix scale" in "Contour tab" is not working for y

### ISSUE THREAD

**Issue by MaikH88** [ZellMechanik-Dresden/ShapeOut#31] opened 2015-10-26 18:46 UTC
When this option is checked, only the Contour accuracy of area is fixed. Contour accuracy of Def is not.

**Comment by paulmueller** [comment] 2015-10-27 08:45
I cannot reproduce this behaviour. Could you please check again? Did you hit apply in the "Contour Plot" tab after checking "Contour Fix Scale"?

**Comment by paulmueller** [comment] 2015-11-02 10:28
Closing because not reproducible. Please reopen if problem persists.

**Closed by paulmueller** 2015-11-02 10:28 UTC
Labels: bug
