### ISSUE TITLE
Showing only images of filtered events in image display panel

### ISSUE THREAD

**Issue by MartaUrb** [ZELLMECHANIK-DRESDEN/ShapeOut#270] opened 2020-04-23 12:49 UTC
This would be an enhancement feature that would make browsing of cell images more convenient for user.

### General information
- Windows 7
- ShapeOut 0.8.7
- Windows 64bit

### Steps to reproduce the problem
e.g.
1. Open Shapeout
2. Load a random dataset
3. Apply some filters, for example 1-1.05 area ratio/porosity
4. Click on a sample datapoint to inspect cell image
5. Go to the cell image area and click "next" to view next contour

### Data files
I worked with .tdms but I don't think it is file-dependant

### Expected behavior
The images are pre-filtered according to the filters applied, i.e. when I click "next" ShapeOut displays only cells that are within applied filters, and skips the filtered-out frames. For example if cell 1,2,3 are retained after filtering and 4 is not (let's say it has porosity=1.09) image display skips it and jumps from frame 3 to frame 5 after "next" is clicked.

### Actual behavior
In the image display region all images are shown, irregardless of applied filters to the dataset.

**Comment by paulmueller** [comment] 2020-04-23 15:12
I thought this might have been a bug (because what you are describing sounds like the way it should be intuitively), but then I realized that this was actually a design thing.

Instead of changing anything in Shape-Out, I would like to propose a workaround for you:
After setting all of your initial filters, create a "filter hierarchy child" in the *Filter* tab. This will generate a new scatter plot with the expected behavior.

I hope this is acceptable...

**Comment by MartaUrb** [comment] 2020-04-23 15:30
Hi! Sure, there are ways around. I can also just click every time on the plot, or screen etc.

I just thought it would be a "nice to have" improvement that you could add at some point, but of course up to you!

**Comment by paulmueller** [comment] 2020-05-19 20:47
As the development of Shape-Out 1 is now mainly limited to bug fixes and my time is limited as well, I am labeling this as "wontfix", closing the issue.

However, I just realized that the Quick View functionality in Shape-Out 2 had the same issue. This is now fixed in Shape-Out 2.1.6. I encourage everyone experiencing this issue to migrate to Shape-Out 2.

**Closed as completed by paulmueller** 2020-05-19 20:47 UTC
Labels: wontfix
