### ISSUE TITLE
Error in ShapeOut

### ISSUE THREAD

**Issue by OttoOliver** [ZELLMECHANIK-DRESDEN/ShapeOut#194] opened 2017-12-08 11:00 UTC
Fluorescence Gating and setting area ratio filter to 1.1 does not work in current version. ShapeOut crashes completely.

**Comment by paulmueller** [comment] 2017-12-08 12:35
Could you please point me to the data with which you experience this problem? How are you gating (using the min/max box filters or the polygon filters)?

**Comment by OttoOliver** [comment] 2017-12-08 20:09
Thanks Paul, We use only min max after compensating. Should I send you the data set?

**Comment by paulmueller** [comment] 2017-12-08 21:30
Yes, please. I am unable to reproduce this with my current test data set.

**Comment by paulmueller** [comment] 2017-12-11 22:16
Please let me know if this has been fixed with issue #195.

**Comment by OttoOliver** [comment] 2017-12-13 09:12
With the new software the error does not occur. Thanks

**Comment by paulmueller** [comment] 2017-12-13 14:47
Ok, closing this one.

**Closed by paulmueller** 2017-12-13 14:47 UTC
Labels: bug
